version: "3.4"
configs:
  prometheus_config:
    file: ./prometheus.yml


networks:
  inner_net:
    driver: overlay
  
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hfv
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017

  knowledge_api:
    image: "knowledge_api"
    ports:
      - "8080:80"
    networks: 
      - inner_net
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo

  prometheus:
    image: knowledge_prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - knowledge_api
    networks:
      - inner_net
      
  grafana:
    image : grafana/grafana
    depends_on: 
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring
    networks:
      - inner_net